### ISSUE TITLE
Completion does not trigger after a '.' character.

### ISSUE THREAD

**Issue by Kraust** [haorenW1025/completion-nvim#1]
Creating this as a result of the flowing thread:
https://www.reddit.com/r/neovim/comments/fhcdzu/a_async_completion_framework_aims_to_support/

**Comment by haorenW1025** [comment]
It should be fixed now. I made a quick fix of this by simply adding detection of character '.' ,  but I'll support trigger character as an option in the next todo(in README). Please update and check.

**Comment by wbthomason** [comment]
Perhaps it would make sense to add a "trigger characters" setting to the configuration in https://github.com/neovim/nvim-lsp, which this plugin could read from? Trigger characters vary widely between languages (e.g. -> and :: in C++, "." in many languages but not others, etc.) and will be useful for any/all completion frameworks based on the built-in LSP client, so this functionality seems to fit better there.

**Comment by haorenW1025** [comment]
Yeah you're right about that trigger characters can be different for different languages, but I think what nvim-lsp is the basic configuration of starting a lsp client, so it would be weird to ask them implement a thing that is used for auto completion framework.
What I'm thinking know is adding an option of trigger character and thus users can modify them
with autocmd, Ex:
```.vim
augroup CompleteionTriggerCharacter
    autocmd!
    autocmd BufEnter * let g:completion_trigger_character = ...
    autocmd BufEnter *.c,*.cpp let g:completion_trigger_character = ...
augroup end
```

**Comment by haorenW1025** [comment]
Trigger Character is now support on the latest branch
By default ['.'] is support, disable it by
```.vim
let g:completion_trigger_character = []
```
or you have multiple trigger character by
```.vim
let g:completion_trigger_character = ['.', '::']
```
close this issue for now, feel free to open it if you have issue about trigger characters!
