### ISSUE TITLE
Floating windows are focusable

### ISSUE THREAD

**Issue by kristijanhusak** [haorenW1025/completion-nvim#10]
Hi,

is there a reason to enable focus on hover windows?
It happens to me sometimes to focus it and then i need to close it manually.

**Comment by haorenW1025** [comment]
Actually the focusable hover windows are the default behavior of neovim built-in hover function. Can you explain more detail of when the focusing happen and how to reproduce it?

**Comment by kristijanhusak** [comment]
I'm not sure how I manage to focus it with keyboard, it just happens as I type randomly. Cannot reproduce it 100% of the time.
Clicking with a mouse definitely focus it. Is there an option to make it non-focusable? I don't really see a reason to be able to focus it.

**Comment by haorenW1025** [comment]
Yeah I agree, sometimes you need to focusing so you scroll through the hover window to see your context but that rarely happens. I can try to make an option to disable it.

**Comment by haorenW1025** [comment]
I disable the focusable window by default(since I think most people won't ever want to focus that). Please update and check:)

**Comment by kristijanhusak** [comment]
Unfortunately i'm still able to focus it, at least with a mouse. Should i add any additional setup?

**Comment by haorenW1025** [comment]
Hmm I think focusing with mouse can't be disable though... I think every floating window should behavior the same. Only way to disable it should be `set mouse=v`.

**Comment by kristijanhusak** [comment]
I know that in vimscript you can disable focusing like this:
```vimL
  call nvim_win_set_config(win, { 'focusable': v:false })
```
Can't that be applied here?

**Comment by haorenW1025** [comment]
Actually I did have this option set, and I'm wrong in the last comment. Focusing floating window is disable now, but only to the automatically hover one. If you manually invoke the hover function it is using the neovim source code and focusable is enable. I think if you actually want the hover window to be not focusable even in the manually triggered hover window, it should be a neovim issue and it's kind of out of the scope of this plugin.

**Comment by kristijanhusak** [comment]
It looks like manual hover is triggered when I open method brackets. Here's an example for tsserver:

```javascript
// test.js

process.exit -> this shows hover, but it's not focusable
process.exit( -> this shows hover, a bit differently, and is focusable
```

Since floating windows are a bit different between those two cases, I assume it's that difference between automatic/manual.

**Comment by haorenW1025** [comment]
Okay my bad, there a misunderstanding though. This is calling the SignatureHelp function and it's not fixed, I'll work on fixing this.

**Comment by haorenW1025** [comment]
It should be fixed now, please update and check!

**Comment by kristijanhusak** [comment]
It works! Thanks!
