### ISSUE TITLE
Is g:completion_enable_fuzzy_match deprecated

### ISSUE THREAD

**Issue by nhooyr** [haorenW1025/completion-nvim#101]
It's in the README but not in the docs and it seems like adding `fuzzy` to `g:completion_matching_strategy_list` does the same.

**Comment by nhooyr** [comment]
I think it was removed in https://github.com/haorenW1025/completion-nvim/pull/71/files but never removed from the README

**Comment by haorenW1025** [comment]
Yep. I should remove it from README. Thanks for the reminder:)

**Comment by haorenW1025** [comment]
It's been removed! Close this for now:)
