### ISSUE TITLE
Problem in vim.schedule callback

### ISSUE THREAD

**Issue by PaulBonnot** [haorenW1025/completion-nvim#103]
In file `lua/completion/matching.lua` line 50, `vim.b` (I guess for buffer variables ?) is indexed without checking if it's `nil`, which creates an error for me since it is (`nil`).

So maybe it could be replaced with something like :

```
    local matcher_list
    if (vim.b and vim.b.completion_matching_strategy_list) then
        matcher_list = vim.b.completion_matching_strategy_list
    else
        matcher_list = vim.g.completion_matching_strategy_list
    end
```

However, changing this I have an other error that pops up during the display of autocompletion menu (see picture)

![05-06-2020_15-12](https://user-images.githubusercontent.com/33038257/83882297-32c9fd80-a742-11ea-8491-1db5335122c8.png)

I used the minimal test.vim for this, and I run the nightly build.

Any idea where the problem is ?

**Comment by haorenW1025** [comment]
`vim.b` is buffer variables which neovim have bulit-in in a PR(https://github.com/neovim/neovim/pull/12268), if you're running into errors like this, please update to the latest nightly release or manually build neovim from master branch.

**Comment by haorenW1025** [comment]
Close this for now, feel free to reopen if you still have any issue.

**Comment by PaulBonnot** [comment]
Thanks man, indeed I thought I used the latest build but I had a bad alias for
it.
