### ISSUE TITLE
Parts of function signature appears inside of parentheses when completing function

### ISSUE THREAD

**Issue by GoldsteinE** [haorenW1025/completion-nvim#105]
https://asciinema.org/a/iRhuclOpzCWDVgPdIGNmrLsR2

**My testing minimal init.vim**
```vim
set runtimepath+=/home/goldstein/.vim/plugged/nvim-lsp
set runtimepath+=/home/goldstein/.vim/plugged/completion-nvim
lua require'nvim_lsp'.rls.setup{on_attach=require'completion'.on_attach}
au Filetype lua setl omnifunc=v:lua.vim.lsp.omnifunc
set completeopt=menuone,noinsert,noselect
```

**How to reproduce**
1. Create a Cargo project and open `src/main.rs`
2. Type `Vec::with_capacity`
3. Hit `^N` to select completion

**Expected behavior**
`Vec::with_capacity` should be completed to the first `(`

**Actual behaviour**
`Vec::with_capacity` is expanded to `Vec::with_capacity(${1:capacity: usize})`

**Comment by haorenW1025** [comment]
I've pushed some update. Right now the behavior should be `Vec::with_capacity(usize)`, which is still not quite the perfect solution, but it is the neovim default behavior. I'm not planning to do some snippet expansion on my side cause that would be too much work, I suggest you use `vim-vsnip` and `vim-vsnip-integ` which has integrate with `completion-nvim` out of the box.
