### ISSUE TITLE
Option g:completion_auto_change_source not works for completion-buffers

### ISSUE THREAD

**Issue by Shatur95** [haorenW1025/completion-nvim#108]
**My testing minimal init.vim**
```vim
imap <A-j> <cmd>lua require'source'.prevCompletion()<CR>
imap <A-k> <cmd>lua require'source'.nextCompletion()<CR>

let g:completion_auto_change_source = v:true
let g:completion_chain_complete_list = {
    \ 'default' : {
    \   'default': [
    \       {'complete_items': ['lsp', 'snippet']},
    \       {'complete_items': ['path'], 'triggered_only': ['/']},
    \       {'complete_items': ['buffers']}]
    \   }
    \}
```

You will also need to have setuped any working LSP.

**How to reproduce**
1. Open any file, for example minimal vimrc from above.
2. Then open any file that have LSP completion. For example, `.cpp` file with setuped `clangd` configuration in vim.
3. Start typing `imap`

**Expected behavior**
LSP have no such words for completion, so completion source changes to `buffers` to complete `imap` word from other opened file.

**Actual behaviro**
LSP have no such words for completion and I have no completion. If I changing completion sourcess manually - I have completion from `completion-buffers`.

**Comment by haorenW1025** [comment]
I guess there are some typos causing this issue. Can you update to the latest branch and see if it's fixed?

**Comment by Shatur95** [comment]
No, the issue still exists :(

**Comment by haorenW1025** [comment]
Try `let g:completion_auto_change_source = 1` instead, at least it works on my side.

**Comment by Shatur95** [comment]
Yes, it works with `let g:completion_auto_change_source = 1`! How this can be possible? Maybe there is a bug in Neovim Lua API?
