### ISSUE TITLE
I can't cycle between all the options using <c-n>

### ISSUE THREAD

**Issue by lourenci** [haorenW1025/completion-nvim#114]
Do you have any idea why the problem in the video is happening?

I can't cycle between all the options. In the video below, I want to select the `months` option, but as soon as the option `Maio$` gets selected the popup is closed. I use `<c-n>` to cycle through the options. When I use `<c-p>`, the popup is closed as soon as I the `Maio` option gets selected.

Thank you for the plugin.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2339362/84796839-80125e80-afcf-11ea-8570-4d27f06351ff.gif)

**Comment by haorenW1025** [comment]
That's weird. Can you post up your minimal config? I can't tell why this is happen by only a screen video.

**Comment by lourenci** [comment]
This is the config for completion-nvim:
```
  let g:completion_confirm_key = "\<C-y>"
  let g:completion_auto_change_source = 1

  augroup EnableAutocomplete
    autocmd!
    autocmd BufEnter * lua require'completion'.on_attach()
  augroup END
```

**Comment by haorenW1025** [comment]
Can I ask about what completion are you using in this video? Is it `lsp` or some `ins-complete` method? I can reproduce it now but it'll be easier if you provide more detail.

**Comment by lourenci** [comment]
I use the default ones together with lsp. In this video, the lsp does not take place yet, I had just opened the js buffer.

**Comment by haorenW1025** [comment]
Please update and check if it's fixed!

**Comment by lourenci** [comment]
Yes. Thank you for that.
