### ISSUE TITLE
New lines being consumed when executing registers.

### ISSUE THREAD

**Issue by fsharpasharp** [haorenW1025/completion-nvim#116]
- Please read through [this section](https://github.com/haorenW1025/completion-nvim/wiki/trouble-shooting) before posting a bug report.

**My testing minimal init.vim**
```
call plug#begin('~/.vim/plugged') 
    Plug 'neovim/nvim-lsp'
    Plug 'haorenW1025/completion-nvim'
call plug#end()
autocmd BufEnter * lua require'completion'.on_attach()
" Set completeopt to have a better completion experience
set completeopt=menuone,noinsert,noselect
```

**How to reproduce**
`qqi<CR><ESC>q@q`

Executing the q register does not insert an extra line.

**Expected behavior**
Executing the q register should insert a new line.

**Extra information**
Can be avoided with the mapping from the documentation:
```
let g:completion_confirm_key = ""
imap <expr> <cr>  pumvisible() ? complete_info()["selected"] != "-1" ?
                 \ "\<Plug>(completion_confirm_completion)"  : "\<c-e>\<CR>" :  "\<CR>"
```

But the default setting should be fixed.

**Comment by haorenW1025** [comment]
Sorry for the wait, it should be fixed by the latest commit, please update and check.

**Comment by fsharpasharp** [comment]
No problem. Thanks for working on this plugin.
