### ISSUE TITLE
g:completion_auto_change_source doesn't work if repeated

### ISSUE THREAD

**Issue by mg979** [haorenW1025/completion-nvim#117]
When I repeatedly press `<C-j>` to change source, it works initially, but then it stops working after the first manual change. This is because `manager.autoChange` is set to `true` on InsertEnter and InsertCharPre, but then [set to false](https://github.com/haorenW1025/completion-nvim/blob/ffa5879c779575d6dc5263988bb213bc82971b62/lua/completion.lua#L158) every time a manual change of source is attempted. So if nothing is found, it isn't reset to `true`. If I delete that line it works better.

**My testing minimal init.vim**
```vim
let $VIMDIR = expand('~/.vim')
set packpath^=$VIMDIR
packadd nvim-lsp
packadd completion-nvim

lua require'nvim_lsp'.sumneko_lua.setup{on_attach=require'completion'.on_attach}
au Filetype lua setl omnifunc=v:lua.vim.lsp.omnifunc

" Use <Tab> and <S-Tab> to navigate through popup menu
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

let g:completion_confirm_key = ""
let g:completion_enable_snippet = 'UltiSnips'
let g:completion_trigger_keyword_length = 2
let g:completion_auto_change_source = 1
let g:completion_chain_complete_list = {
      \ 'default': [
      \    {'complete_items': ['snippet']},
      \    {'mode': 'file'},
      \    {'mode': 'keyn'},
      \    {'mode': 'omni'},
      \    {'mode': 'c-n'},
      \]}

autocmd BufEnter * lua require'completion'.on_attach()
imap <c-j> <cmd>lua require'source'.nextCompletion()<CR>

" Set completeopt to have a better completion experience
set completeopt=menuone,noinsert,noselect
```

**How to reproduce**
I'm pressing repeatedly `<C-j>` there
https://asciinema.org/a/L40VffIyJOp8t34I7hYYuZPaD
When a chain doesn't yield results, it still doesn't change automatically.

**Expected behavior**
`manager.autoChange` should work without interruptions, always skipping empty chains at least until a full cycle is attempted.

**Comment by haorenW1025** [comment]
Oh I thought that user don't want it to keep changing source if it's manually changing, that's why I set `manager.autoChange` to true when manually changing. I can change that though.

**Comment by haorenW1025** [comment]
Should be fixed.

**Comment by mg979** [comment]
Thanks.
