### ISSUE TITLE
lua/source/lsp.lua:14: bad argument #1 to 'pairs' (table expected, got nil)

### ISSUE THREAD

**Issue by lithammer** [haorenW1025/completion-nvim#14]
I get the following when using [microsoft/python-language-server](https://github.com/microsoft/python-language-server) before the server is fully ready. So if I for example start typing immediately after opening a file. Seems like it's specific to ms-pyls though.

>Error executing vim.schedule lua callback: ...vim/pack/packager/opt/completion-nvim/lua/source/lsp.lua:14: bad argument `#1` to 'pairs'
(table expected, got nil)

**Comment by haorenW1025** [comment]
It should be fixed now, but I'm experiencing some lag when using pyls-ms, it usable now but not perfect, I'll work on fixing the lagging issue.

**Comment by lithammer** [comment]
I can confirm that the "bad argument" error is resolved at least, thanks!

**Comment by haorenW1025** [comment]
Yeah, the lagging issue is because I made a change recently, causing the LSP not working in async mode as expected... I changed it back so it should be fixed. close this for now, feel free to open it if any issue happen!
