### ISSUE TITLE
Signature help floating window does not close when removing parentheses

### ISSUE THREAD

**Issue by kevinrambaud** [haorenW1025/completion-nvim#16]
Hi, well done for this plugin, it's excellent! 

I have an issue with the signature help floating window that does not disappear is some cases. The main one happens when I add parentheses when calling a method or function and then remove these parentheses.

For example, in javascript calling `console.log()` makes the floating window appears, removing the `()` does not make it disappear. It only goes away when I exit the insert mode.

I suspect it comes from this line https://github.com/haorenW1025/completion-nvim/blob/master/lua/signature_help.lua#L84 but I'm not enough familiar with vim scripting or lua to come up with the appropriate fix.

**Comment by haorenW1025** [comment]
It should be fixed now, please update and check:)

**Comment by kevinrambaud** [comment]
It works well now 👍Thanks!
