### ISSUE TITLE
Bug with completion - inserting what should be metadata 

### ISSUE THREAD

**Issue by offendo** [haorenW1025/completion-nvim#19]
Hello,

When using the auto-completion (with `ccls`, in my case), extra info along with the selected word is being inserted, as shown in the gif.

Using NVIM v0.5.0-418-g87d892afa, if it matters at all. Thanks for the help!

![completion-bug](https://user-images.githubusercontent.com/29783125/77961980-b847b200-72a8-11ea-8076-a886c25c6f2c.gif)

**Comment by haorenW1025** [comment]
Yeah I've encounter this issue before, but sadly it's out of the scope that I can solve cause the message simply came from the language server. Use ccls without completion-nvim and directly use omni-complete will still have this issue. Maybe posting an issue on neovim or nvim-lsp might help. Also, I recommend using clangd as c/c++ language server cause it doesn't have this kind of issue and it's pretty fast.

**Comment by offendo** [comment]
Ah okay, thanks anyway! I'll try out clangd.

**Comment by haorenW1025** [comment]
Hey just want to notify that this [PR](https://github.com/neovim/neovim/pull/11989) should solve this issue!

**Comment by offendo** [comment]
Fantastic, thanks! Appreciate the update
