### ISSUE TITLE
"Pattern not found" message constantly being sent on new text

### ISSUE THREAD

**Issue by tjdevries** [haorenW1025/completion-nvim#21]
Hey, Love the plugin!

Having a small problem that I'm not sure why this is happening. Whenever I type something that doesn't exist in the current buffer (or as a valid completion) I get a message on every keystroke like

```
|| Pattern not found
|| Pattern not found
|| Pattern not found
|| Pattern not found
```
Is there some configuration option you know of that I might have missed? 

Completeopt is what is recommended in the setup guide. 

Thanks

**Comment by haorenW1025** [comment]
Can you please check if `g:completion_auto_change_source` is set to 1 or not? If so this might because the plugin is auto changing source to an `ins-complete` method and due to the nature of `ins-complete` it will show "Pattern not found" as a result. If not please provide more detail of your config. Thanks!

**Comment by tjdevries** [comment]
So it appears that `g:completion_auto_change_source` is set to 0

Some configuration:

```
completeopt=menuone,noinsert,noselect
omnifunc=lsp#omnifunc
complete=.,w,b,u,t

" Completefunc is empty
completefunc=

['completion_enable_focusable_hover', 0]
['completion_enable_auto_signature', 1]
['completion_trigger_character', ['.']]
['completion_enable_in_comment', 0]
['completion_enable_auto_hover', 1]
['completion_max_items', v:null]
['completion_enable_snippet', v:null]
['completion_confirm_key_rhs', '']
['completion_confirm_key', '^M']
['completion_trigger_keyword_length', 1]
['completion_chain_complete_list', [{'ins_complete': v:false, 'complete_items': ['lsp', 'snippet']}, {'ins_complete': v:true, 'mode': '<c-p>'}, {'ins_complete': v:true, 'mode': '<c-n>'}]]
['completion_auto_change_source', 0]
['completion_enable_auto_popup', 1]

```

**Comment by tjdevries** [comment]
Also, weirdly I'm currently seeing the problem only in lua files, so maybe it's something else in my configuration. I can look around more, I at least wanted to confirm that that was *not* supposed to be happening :)

**Comment by haorenW1025** [comment]
Yeah that is not supposed to happen if `g:completion_auto_change_source` is set to 0. I'm using lua language server and it doesn't have this issue... Can you check if this still happens using a clean environment? Put the below line in a file like `test.vim`
```.vim
call plug#begin('~/.vim/plugged') 
    Plug 'neovim/nvim-lsp'
    Plug 'haorenW1025/completion-nvim'
call plug#end()
lua require'nvim_lsp'.sumneko_lua.setup{on_attach=require'completion'.on_attach}
au Filetype lua setl omnifunc=v:lua.vim.lsp.omnifunc
" Use <Tab> and <S-Tab> to navigate through popup menu
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

" Set completeopt to have a better completion experience
set completeopt=menuone,noinsert,noselect
```
and use `vim -u test.vim test.lua` and see if it still happen

**Comment by tjdevries** [comment]
Yeah, I'll check that out later today and tomorrow and get back to you. Will also bisect some of my configs and see if it's my fault somewhere :) I will let you know the result later.

**Comment by tjdevries** [comment]
Ah, it wasn't your fault, it appears it was because I didn't have shortmess set up well:

With this, it is fixed. You might want to just add this as an info somewhere in the docs though.

```vim
" Don't show the dumb matching stuff.
set shortmess+=c
```

**Comment by haorenW1025** [comment]
OK, I've added that to README, thanks for the trouble shooting!
