### ISSUE TITLE
Cursor jumps to the end when completing

### ISSUE THREAD

**Issue by kristijanhusak** [haorenW1025/completion-nvim#22]
While i was setting up vim, i noticed that cursor jumped to the end for some characters. You can see in gif what is my configuration.
Note that i tried both with and without auto pairs plugin, but still same.
Here's the gif:

![completion](https://user-images.githubusercontent.com/1782860/78586549-e0e92200-783b-11ea-967f-1f4c8496ec9a.gif)

**Comment by kristijanhusak** [comment]
Here's one more that happened in sql:
![completion-sql](https://user-images.githubusercontent.com/1782860/78587167-da0edf00-783c-11ea-8f2e-02c4a5027b01.gif)

**Comment by haorenW1025** [comment]
Can you follow the step in ![here](https://github.com/haorenW1025/completion-nvim/wiki/trouble-shooting)? Cause from my side I wasn't able to reproduce it.
![Kapture 2020-04-07 at 1 45 26](https://user-images.githubusercontent.com/35623968/78588834-dfd2e780-7871-11ea-887e-33219273dc33.gif)

**Comment by kristijanhusak** [comment]
Yeah it works with min vimrc. I'll try to figure out what's happening and write it here. Thanks.

**Comment by kristijanhusak** [comment]
Found it. It's [vim-rsi](https://github.com/tpope/vim-rsi) causing the issue.
Sorry for bothering.
