### ISSUE TITLE
Completion source sorting

### ISSUE THREAD

**Issue by kristijanhusak** [haorenW1025/completion-nvim#24]
Hi,

When i initially started using the plugin with ultisnips, my snippets completion was sorted ok. Now, i noticed it's not sorted correctly. Is this something that is handled by completion-nvim or it's just printed out how ultisnips returns it?

Here's the screenshot:
![screenshot](https://i.imgur.com/rbt8BKN.png)

I would expect items to be sorted like this:
```
cl
cla
clac
clax
clearq
click
clone
```

**Comment by haorenW1025** [comment]
There a small bug in a commit that causes items not sorted correctly. I fix that in the latest commit. But initially I only sort items with respect to length, so it'll be more like
```
cl
cla
clac
clax
click
clone
clearq
```
Is this a reasonable solution? Or will sorting in alphabetical order help with others thing?

**Comment by kristijanhusak** [comment]
This looks good, thanks!
