### ISSUE TITLE
Enable/Disable completion in strings

### ISSUE THREAD

**Issue by lithammer** [haorenW1025/completion-nvim#26]
Similar to the option to enable/disable completion in comments, it would be nice with an option to also enable/disable them in strings. Mostly for the same reasons they're annoying in comments.

**Comment by haorenW1025** [comment]
In fact, right now the scope completion is implemented, so you can customize how you want in every syntax group (see [wiki](https://github.com/haorenW1025/completion-nvim/wiki/chain-complete-support) for more detail)

You can simply do it by putting this into your init.vim
```.vim
 let g:completion_chain_complete_list = {
    \ 'default' : {
    \   'default': [
    \       {'complete_items': ['lsp', 'snippet']},
    \       {'mode': '<c-p>'},
    \       {'mode': '<c-n>'}],
    \   'comment': [],
    \   'string': []
    \   }
    \}
```
which will set the completion list in string to nothing therefore disable completion in string.
