### ISSUE TITLE
Ultisnips does not expand

### ISSUE THREAD

**Issue by kuator** [haorenW1025/completion-nvim#27]
I've been using coc.nvim for a long time. And I really like it's behaviour 
That's why I use `set completeopt=menuone,noinsert`  instead of `completeopt=menuone,noinsert,noselect`. The problem now that ultisnips does not work with these settings, snippets don't expand.

**Comment by haorenW1025** [comment]
Should be fixed now, please update and check:)

**Comment by kuator** [comment]
Amazing
