### ISSUE TITLE
Is it possible for plugin to insert parentheses?

### ISSUE THREAD

**Issue by kuator** [haorenW1025/completion-nvim#28]
Let's say I have the following line
![2020-04-09-130512_263x82_scrot](https://user-images.githubusercontent.com/25168308/78867535-12900200-7a63-11ea-92fd-8eae556042dd.png)
When I press enter, it expands to following
![2020-04-09-130614_231x53_scrot](https://user-images.githubusercontent.com/25168308/78867618-33585780-7a63-11ea-86d5-8cdbf06b871c.png)
Is it possible to make plugin insert parentheses for me?
![2020-04-09-130659_189x50_scrot](https://user-images.githubusercontent.com/25168308/78867693-4ec36280-7a63-11ea-8b6c-d8879bcb86de.png)

**Comment by haorenW1025** [comment]
Hmm I have to look into and see if it's possible. May takes some time though.

**Comment by kuator** [comment]
> Hmm I have to look into and see if it's possible. May takes some time though.

https://github.com/hrsh7th/vim-vsnip
I think this plugin might do something like this.

**Comment by haorenW1025** [comment]
I've tried a little bit, but I find out that it works better when `completeopt` is set to `noselect`, otherwise sometimes it will not work...
You can sure try it first, You need to specify an option `let g:completion_enable_auto_paren = 1`.

**Comment by kuator** [comment]
Thanks for the plugin! :smile:
