### ISSUE TITLE
signature help appears behind completion list if list width + sighelp width is larger than the screen size

### ISSUE THREAD

**Issue by mattbailey** [haorenW1025/completion-nvim#3]
<img width="1130" alt="Screen Shot 2020-03-12 at 12 46 16 PM" src="https://user-images.githubusercontent.com/216331/76561210-0dd62f00-6460-11ea-8b94-7d2db6154768.png">

**Comment by haorenW1025** [comment]
<img width="628" alt="Screen Shot 2020-03-13 at 11 09 31 AM" src="https://user-images.githubusercontent.com/35623968/76586373-9e257a00-651b-11ea-95bd-7725995d847a.png">
should be fix now, now floating window will respect the amount of area you left, please update and check:)

**Comment by mattbailey** [comment]
Hmm... closer (and much more usable), but still behind the tab dropdown and now the last line in the sighelp is cut off.

<img width="1687" alt="Screen Shot 2020-03-13 at 7 42 44 AM" src="https://user-images.githubusercontent.com/216331/76631214-88ee2280-64fe-11ea-9532-0fce27c42aba.png">

(awesome work on this plugin btw)

**Comment by haorenW1025** [comment]
I'm sorry, there's a typo which make it still blocking the popup menu. It should be fixed in the latest branch. But for the cutoff part, it's hard to change it since it requires changing neovim's source code(since I copy them to my local file and modify them) and it might take some time.

**Comment by mattbailey** [comment]
Awesome, thanks. Can confirm it's no longer behind the tab selection.

**Comment by haorenW1025** [comment]
I've made a change to add a new line if the text is too long, it should solve the cutoff issue. Also note that the newline is added to the nearest white space, but if the text is too long and with no white spaces, it will still be cutoff(but this case happens rarely).
Ex:
Normal behavior
![Screen Shot 2020-03-14 at 1 30 29 AM](https://user-images.githubusercontent.com/35623968/76645365-d36dae80-6593-11ea-96bd-31b9a443b872.png)
When window is too small
![Screen Shot 2020-03-14 at 1 30 15 AM](https://user-images.githubusercontent.com/35623968/76645374-d7013580-6593-11ea-896e-7105f1e3c623.png)
