### ISSUE TITLE
Add delay between keypress and autocomplete pop-up

### ISSUE THREAD

**Issue by subsonik** [haorenW1025/completion-nvim#32]
Hi,

First of all, thanks for creating this plugin, I've been looking for a _good_, fast, and minimal autocomplete plugin for Neovim's native LSP implementation for a while, this one fits the bill nicely! :)

Just one small feature request: would it be possible add a _configurable_ amount of delay between pressing a key and having the completion pop-up window open? 

It's a little distracting to be typing away and having the box constantly flickering away below the cursor. Adding maybe 150-200ms delay would help a great deal with my focus.

Thanks.

**Comment by haorenW1025** [comment]
Thanks for the kind word!
The auto completion engine is actually control in a timer. I've added an option to adjust the timer cycle, set it up by
```.vim
let g:completion_timer_cycle = 200  "default value is 80
```
Please update and see if it works!

**Comment by subsonik** [comment]
Wow that was fast! It works like a dream, thank you!
