### ISSUE TITLE
ultisnip error

### ISSUE THREAD

**Issue by teto** [haorenW1025/completion-nvim#33]
Setting `let g:completion_enable_snippet = 'UltiSnips'` without ultisnips triggers the following error:

```error executing vim.schedule lua callback: ...l/share/nvim/site/completion-nvim/lua/source/snippet.lua:8: Vim:E117: Fonction inc
onnue : UltiSnips#SnippetsInCurrentScope
```
in general i dont mind these but due to the nature of the plugin, vim loops over the error and it becomes hard to quit. Maybe it could ignore the error and provide a check via checkhealth (see `:help health-dev`).

**Comment by haorenW1025** [comment]
Thanks for the suggestion! I've added a checking to see if snippets engine is available or not. I would definitely work on `checkhealth` if I have some spare time:)

**Comment by teto** [comment]
a bit of a different issue but not sure it was worth a new issue: 
when defining this variable:
```
let g:completion_chain_complete_list = {
    \'default' : {
    \	'default' : [
    \		{'complete_items' : ['lsp', 'snippet']},
    \		{'mode' : 'file'}
    \	],
    \	'comment' : [],
    \	'string' : []
    \	},
    \'vim' : [
    \	{'complete_items': ['snippet']},
    \	{'mode' : 'cmd'}
    \	],
    \'c' : [
    \	{'complete_items': ['ts']}
    \	],
    \'python' : [
    \	{'complete_items': ['ts']}
    \	],
    \'lua' : [
    \	{'complete_items': ['ts']}
    \	],
    \}

```
with the treesitter plugin uninstalled, I got

`Error executing vim.schedule lua callback: ...to/.local/share/nvim/site/completion-nvim/lua/source.lua:140: attempt to index loc
al 'complete_items' (a nil value)`

**Comment by haorenW1025** [comment]
It should be fixed in the latest commit, I'll also include checking if the complete_items is available in `:checkhealth`. Thanks a lot for reporting!

**Comment by teto** [comment]
you are fast ! yes that fixed it. Looking forward to the checkhealth component !
