### ISSUE TITLE
Add ability to leave confirm key empty

### ISSUE THREAD

**Issue by TravonteD** [haorenW1025/completion-nvim#34]
I'd like to not have confirm key set and just go through the menu using the default `<C-n>`  & `<C-p>`.
Currently setting `g:completion_confirm_key = ""` causes an error, It would be great if this disabled the mapping instead.

**Comment by haorenW1025** [comment]
The PR solves it. However you should be aware that having no confirm key means that snippets expansion won't work.

**Comment by TravonteD** [comment]
I personally don't use the snippet expansion. Maybe a note should be made in the docs to warn new users?
