### ISSUE TITLE
Support for function argument snippets (recent Neovim commit)

### ISSUE THREAD

**Issue by subsonik** [haorenW1025/completion-nvim#37]
Hi,

It seems that one of the latest Neovim commits (https://github.com/neovim/neovim/commit/e6cfc1b158506f8d2a4b598d07051b7f3de5f964) adds support for returning function argument snippets, which completion-nvim doesn't seem to have support for? (see pic).

Would it be a lot of work for you to implement support for this?

Or maybe there's some other plugin I can use to handle these? I tried Ultisnips but that didn't seem to work.

Thanks!

<img width="275" alt="Screenshot 2020-04-22 at 08 01 10" src="https://user-images.githubusercontent.com/18307500/79946193-fe82d200-845e-11ea-9637-1f80021d3d47.png">

**Comment by haorenW1025** [comment]
Hmm I'll have to look into it and see can it be possible to manage it in completion-nvim.

**Comment by haorenW1025** [comment]
@subsonik May I ask what language server are you using in the pic? Cause the language server I used doesn't have much difference after the new commit.

**Comment by haorenW1025** [comment]
Hmm I think this requires some time to fix... Since my knowledge for rust is very limited, it would be nice if you can provide some code snippets for me.

**Comment by haorenW1025** [comment]
After some research I think snippets expansion and support is kind of out of the scope of this plugins. I removed the snippets items for now, there are some snippet engine for lsp snippet expansion though([vsnip](https://github.com/hrsh7th/vim-vsnip)], I'll try to reach out for them and see if we can support it.

**Comment by subsonik** [comment]
Very nice, thank you @haorenW1025! 👍

**Comment by haorenW1025** [comment]
@subsonik Just mention that integration with `vim-vsnip` is up now. I've tested it with rust-analyzer, works pretty nice!
