### ISSUE TITLE
Chained completions support

### ISSUE THREAD

**Issue by vigoux** [haorenW1025/completion-nvim#4]
I don't know if you've ever tried [mucomplete](https://github.com/lifepillar/vim-mucomplete), but the completion mecanism there is really nice, and only using built-in features.

The way it works is it tries each completion method in a predefined list, and offers you :
* The first which work as current completion method
* A way to navigate between completion methods and select the one you want

It is really useful for two reasons :
* Most of the time you only want syntaxic completion, and this only, without snippets which are filling completion list
* When using completion in another way (snippets for example), you don't really know their name.

**Comment by haorenW1025** [comment]
Let me first look at mucomplete and see how we can integrate it:)

**Comment by haorenW1025** [comment]
This issue may takes some times... I'll try to get `ins-completion` to work first.

**Comment by vigoux** [comment]
No worry, tell me if you want some help on anything, I am going to work on the treesitter integration, and trying to understand how it works.

We might even be able to have a treesitter completion source.

**Comment by haorenW1025** [comment]
Get some good progress on the chained completion, still need to fix some major bug before pushing though.
![Kapture 2020-03-15 at 1 49 48](https://user-images.githubusercontent.com/35623968/76687511-b2728f80-665f-11ea-9cfc-acd317225dc0.gif)

**Comment by vigoux** [comment]
Ooooh that's awesome ! I am working on a treesitter completion source, which would allow us to have completion of items in current scope !

Can't wait for this feature !

**Comment by haorenW1025** [comment]
I decided to push the first version for which you can changing completion source manually  by
```.vim
imap <c-j> <cmd>lua require'source'.prevCompletion()<CR>
imap <c-k> <cmd>lua require'source'.nextCompletion()<CR>
```
The automatically changing source feature still have some issues to fix, I disable it by default for now, but if you want to test it out, you can use `let g:completion_auto_change_source = 1
`(get ready to run into a lot of issue though).

I refactor the code a lot, if you're trying to add other completion source, please look at `source.lua`, `source/lsp.lua` and `source/snippet.lua` for reference. Feel free to ask me if you have any question or unexpected behavior occurs!

**Comment by haorenW1025** [comment]
Aside from try solving issue with the auto changing source option, I'll work on user option to customize their source which can let us have a better code base to work on syntax aware completion in the future.

**Comment by kristijanhusak** [comment]
I have one suggestion to add. It would be great to introduce looping through these completions. So when it comes to the end, instead of saying "no next completion method", it will just start from the beginning.

**Comment by vigoux** [comment]
> I have one suggestion to add. It would be great to introduce looping through these completions. So when it comes to the end, instead of saying "no next completion method", it will just start from the beginning.

I am going to look into it right now.

**Comment by haorenW1025** [comment]
I've been solving bugs for chain-completion lately, I think it's probably good to go, I've updated on README and also make an option for customize your own completion list. Please check! Close this for now but feel free to open another issue if you encounter some issue!
