### ISSUE TITLE
lua callback erorr

### ISSUE THREAD

**Issue by ckipp01** [haorenW1025/completion-nvim#41]
I may be totally missing something here, but I'm continually getting the same error, and I'm unsure what's causing it. I tried using the minimal `test.vim` that you have in your wiki, and I still get the error.

I installed [metals](https://github.com/neovim/nvim-lsp/blob/master/lua/nvim_lsp/metals.lua) using the `LspInstall metals` command outlined in `nvim-lsp` and the only thing I have in my minimal `test.vim` file is different is the following line changed for metals.

```lua
lua require'nvim_lsp'.metals.setup{on_attach=require'completion'.on_attach}
```
When I open a `.scala` file, I can see in the server trace file that everything has started as expected but the moment I start typing I am greeted with this:

```
Error executing vim.schedule lua callback: /Users/ckipp/.vim/plugged/completion-nvim/lua/utility.lua:30: attempt to call field 'tbl_filter' (a nil value)
```

Any insight would be greatly appreciated.

I'm on:
- MacOS
- iTerm2
- NVIM v0.5.0-3d1531a

**Comment by haorenW1025** [comment]
Can you check if compiling neovim from the latest master help solving this issues? I think `tbl_filter` is only support in a rather new version. Notify me again if this doesn't work, thanks!

**Comment by ckipp01** [comment]
> Can you check if compiling neovim from the latest master help solving this issues? I think `tbl_filter` is only support in a rather new version. Notify me again if this doesn't work, thanks!

Ah, that indeed did fix the issue. Thank you!

**Comment by haorenW1025** [comment]
No problem, I'm working on some `checkhealth` integration and I'll put this check in it, thanks for the report!
