### ISSUE TITLE
UltiSnips auto extension does not work with pumvisible

### ISSUE THREAD

**Issue by weilbith** [haorenW1025/completion-nvim#44]
Hi,
thanks for this cool plugin!
Unfortunately does the automatic extension of snippets which are marked like that by UltiSnips not work anymore when the PUM is visible. How can I restore that?

**Comment by haorenW1025** [comment]
Sorry but can you elaborate more on how to reproduce the issue cause I cannot get it.

**Comment by weilbith** [comment]
Haha, sorry my report was too short.
So I have some snippets for Ultisnips which use the autotrigger functionality (see `:h UtliSnips-autotrigger). So I added the `A` modifier to a few of my snippets. In short: if you type the trigger of the snippet, the snippet becomes extended automatically without manual keymap or suggestion selection.
But since I use this plugin, this does not work anmymore. I was able to limit this to the popup menu of completion candidates. This opens while typing the trigger, because I enabled snippet completion. So I could no select the snippet from the list. But these autotrigger snippets should not require such action. So if I now hit delete in insert mode the completion popup closes. Typing the last letter of the snippet trigger again does work now, since the completion menu can't open that fast again.

Exact example. I have the following snippet for the filetype `vim`:

```vim
snippet augroup "autocommand group declaration" bA
augroup ${1:name}
	autocmd!
	autocmd $0
augroup END
endsnippet
```

I you now open a random `.vim` file and type at the begin of a line (ignoring spaces) the trigger `augroup`, then you get the full snippet completed, the cursor on the `${1:name}` field. This works for me because there is never a situation when I don't want to complete this snippet if I type `augroup` on a new line. 
Having now `completion-nvim` in place with snippet completion and I type `augroup` I see the popup with this snippet as well as an entry from the `vimls` that `augroup` is an operator I could complete. After all: it does not autotrigger. I have to manually select the snippet suggestion. So instead of no action, I need 3 additional keystrokes (2x down in the popup menu and one to select). Or I could delete the last characte and type it again, which are just 2 strokes. Cost more brain power, is confusing and after all not automatic. :wink:

**Comment by haorenW1025** [comment]
Okay I got it. I'll try to find out what went wrong. Thanks for the detail information:)

**Comment by haorenW1025** [comment]
That's weird cause I can't reproduce it on my side. I'm using the snippets you provide and a minimum `init.vim` and the snippet will be auto expand when you type the trigger word or the select items from popup menu.
![Kapture 2020-04-26 at 19 38 45](https://user-images.githubusercontent.com/35623968/80306397-a698f200-87f5-11ea-9e9e-057708bfd934.gif)

The testing init.vim is as bellow
```vim
set runtimepath+=~/.vim/plugged/nvim-lsp
set runtimepath+=~/.vim/plugged/completion-nvim
set runtimepath+=~/.vim/plugged/diagnostic-nvim
set runtimepath+=~/.vim/plugged/ultisnips
set runtimepath+=~/.vim/plugged/vim-snippets

lua require'nvim_lsp'.vimls.setup{on_attach=require'on_attach'.on_attach}
au Filetype lua setl omnifunc=v:lua.vim.lsp.omnifunc

" Set completeopt to have a better completion experience
set completeopt=menuone,noinsert,noselect

let g:completion_enable_snippet = 'UltiSnips'
```

**Comment by weilbith** [comment]
Hmm okay. Thanks for the input. Then I need to verify my own NeoVim setup and checkout what cause the problem. Thanks that you tested it and posted the video!
I'll maybe post an update here if it was something that could be interesting and not just very special to my setup.
