### ISSUE TITLE
Sort suggestions by kind priority

### ISSUE THREAD

**Issue by gbrlsnchs** [haorenW1025/completion-nvim#45]
Hi! First of all, thanks for this nice plugin. Works neat!

When I'm programming in JavaScript, when suggestion for objects appear (e.g. after typing `obj.`), many variables show up in the suggestions, most are of kind `File`, while the ones of kind `Field` (the object fields) get lost throughout all suggestions.

Now, I'm not sure what's the ideal solution, but it would be nice if kinds like `Field` had priority over ones like `File`, so the first suggestions that show up are the object fields.

**Comment by haorenW1025** [comment]
I've added an option to let user set the priority of complete items, you can set it up by
```vim
let g:completion_items_priority = {
        \ 'Field': 5,
        \ 'Function': 5,
        ...
        \}
```
Higher the priority is, it will more likely be the top suggestion. Also if you doesn't specify the priority of the items, it'll simply be 1.(In your use case, you can also specify the priority of File to be 0)
Please update and let me know if it works:)

**Comment by gbrlsnchs** [comment]
Wow, thanks! It worked perfectly. Totally solved. I'm closing this and, if something breaks, I'll open a new issue. Thanks again!

**Comment by ldelossa** [comment]
@haorenW1025 this is pretty close, but completion does not seem to be aware of its context. 

For instance in Go, even if I prioritze Fields to be higher, I get field suggestios not relevant to the struct I'm currently inside.
