### ISSUE TITLE
lua callback error: 'make_text_document_params' (a nil value)

### ISSUE THREAD

**Issue by fdschmidt93** [haorenW1025/completion-nvim#47]
Hi,

the plugin works great on my local machine. But after setting it up on ssh (with fresh installs of dotnet and nvim-lsp + pyls_ms) I continuously run into 

/nvim/plugged/completion-nvim//lua/completion/hover.lua:344: attempt to call field 'make_text_document_params' (a nil value)

The LSP is working (linting, vim.lsp.buf.'function' for renaming, go-to definition, hover, etc.), but - as you'd expect from the error - hover at completion does not work.

Many thanks for your help!

Versions:
NVIM v0.5.0-477-gf9055c585
dotnet - v3.1.3 SDK

**Comment by haorenW1025** [comment]
Hmm I'll suggest using the latest master of neovim, manually compiles it and see if that solve the issue. Notify me again if that doesn't work, thanks:)

**Comment by fdschmidt93** [comment]
Good stuff! Many thanks, works now.

Issue came up, because I lazily updated nvim by extracting the appimage (on ssh) and then only moved the nvim binary in the respective folder and thereby was apparently missing the updates that should have been in /local/share/nvim/runtime, in which the required make_text_document_params function is also implemented.
