### ISSUE TITLE
Get list of trigger characters from LSP capabilities

### ISSUE THREAD

**Issue by clason** [haorenW1025/completion-nvim#48]
Some LSP servers provide a list of reasonable trigger characters as part of their `completionProvider` capabilities. If this is the case, completion-nvim should use them as the default in place of `.`. (See https://github.com/prabirshrestha/asyncomplete-lsp.vim/blob/5c470ae8e58c8762dc4c669b38fa5649b57f53e3/plugin/asyncomplete-lsp.vim#L30 for reference.)

**Comment by haorenW1025** [comment]
Great suggestion! Never notice that before, will start to work on that:)

**Comment by clason** [comment]
Really excited about the plugin, it's insanely fast!

**Comment by haorenW1025** [comment]
Thanks for the kind word:)
This has been fixed in the latest commit, and also because of this feature, the default trigger character is now `[]`, it will be served as an addition to the lsp trigger character.

**Comment by clason** [comment]
Great, works like a charm! Thanks!
