### ISSUE TITLE
Error vim.schedule lua callback, attempt to index a nil value

### ISSUE THREAD

**Issue by kristijanhusak** [haorenW1025/completion-nvim#49]
At random I get this error:
```
Error executing vim.schedule lua callback: .../nvim/pack/packager/start/completion-nvim/lua/source.lua:73: attempt to index a nil value
```
I can reproduce it 100% of the time by editing lua files, and for some other file types happens randomly. Note that I don't have lsp for lua set up, so maybe that's the issue.

This is my config:
```vimL
let g:completion_chain_complete_list = {
      \ 'default': [
      \    {'complete_items': ['lsp', 'snippet', 'path']},
      \    {'mode': 'tags'},
      \    {'mode': 'keyn'},
      \    {'mode': '<c-p>'},
      \  ]}
```

**Comment by haorenW1025** [comment]
I messed something up in the latest change, it should be fixed now.

**Comment by kristijanhusak** [comment]
Looks good, thanks!

**Comment by ofrades** [comment]
I am getting `Error executing vim.schedule lua callback: ....vim/plugged/completion-nvim/lua/completion/matching.lua:59: attempt to call a nil value`
