### ISSUE TITLE
[Feature] Show complete item "info" as signature

### ISSUE THREAD

**Issue by kristijanhusak** [haorenW1025/completion-nvim#50]
Hi,

what do you think about showing selected complete item `info` property as signature beside the autocompletion, in situations where it is not empty? I have a custom completion that provides `info` with some details, but i'm not sure how to show it.

**Comment by haorenW1025** [comment]
Right now I'm using `user_data` for this use cases cause I want to separate `hover` and `signature_help` for popup. You can look at `lua/source/snippet.lua` or the following code
```lua
      local user_data = {hover = things that you want to show in hover window}
        table.insert(complete_items, {
          ...
          user_data = vim.fn.json_encode(user_data)
        })
```
It should be shown correctly once you put the correct `user_data` in it.

**Comment by kristijanhusak** [comment]
That works, thanks!
