### ISSUE TITLE
Hover window goes off screen at times causing an error

### ISSUE THREAD

**Issue by ckipp01** [haorenW1025/completion-nvim#53]
I noticed today when I had my terminal split that the hover window was going off too far to the right. I'm not 100% sure what is actually causing this, but it also caused an `Error` to appear as well. Here is a screen shot of what I mean for the window going too far:

<img width="829" alt="Screenshot 2020-05-02 at 10 11 20" src="https://user-images.githubusercontent.com/13974112/80858937-51c60300-8c5d-11ea-9b62-68cddbd64b9d.png">

The arrow is pointing towards the edge of my terminal, and see how it's cutting the floating window. Then the following `Error` is appearing:

```
Error executing vim.schedule lua callback: ...pp/.vim/plugged/completion-nvim/lua/completion/hover.lua:220: 'width' key must be a positive Integer
```

If you need any help with reproduction or any more details, please let me know. I'm using this with [Metals](https://github.com/scalameta/metals) installed via `LspInstall` from `neovim/nvim-lsp`.

Thanks for you great work!

**Comment by haorenW1025** [comment]
It should be fixed in the latest update. Please update and check:)

**Comment by ckipp01** [comment]
Perfect. That indeed does seem to fix it. Thanks for the quick reply and fix!
