### ISSUE TITLE
Path completion of files/directories with spaces in the name

### ISSUE THREAD

**Issue by JanValiska** [haorenW1025/completion-nvim#55]
Hi @haorenW1025 , firstly thank you for super completion plugin. I use it on daily basis for home and work tasks.

Unfortunately, when i try to complete path for example: "~/Directory/With spaces/", the `Directory` part is suggested correctly but completion of inner directory is divided into two suggestions: 'With', 'spaces'.

I tried look to source code and it seems that you use system `ls` command to retrieve list of files/directories and after that you match listed files by `%S+` which matches only one word without spaces. Pity i can't help since i don't know lua language. 

Also sorry for my English language :)

**Comment by JanValiska** [comment]
Maybe `find ./  -mindepth 1 -maxdepth 1 -printf "%f\n"` will do the trick. And in `onread` function match whole lines.

**Comment by haorenW1025** [comment]
It should be fixed now, please update and check.

**Comment by JanValiska** [comment]
I tested it and it works in all basic scenarios. Thank you for fix.

**Comment by haorenW1025** [comment]
I've found out some specific issues though. Right now when trying to complete `" a b ../"` won't work because I have to respect to spaces...Any thought on how should I solve this?
Also I've found out even the built-in file completion of vim doesn't support completion of filename with spaces(You can complete, but can't get into the directory with spaces) and I can see why. It's quite difficult to consider all situation with spaces in file name and normally file name won't include spaces too. Any reasons about why including space is a must?

**Comment by JanValiska** [comment]
Some reasons to include space support in path completion are:
- It is natural since all filesystems that i'm aware of supports file and directories with spaces in their name
- I use vimwiki plugin and there are many files with spaces in their name. It is very helpful if your plugin can complete these wiki links.

Maybe we can be inspired by [Deoplete file source.](https://github.com/Shougo/deoplete.nvim/blob/master/rplugin/python3/deoplete/source/file.py) In Deoplete file completion works even in `"a b ../"` scenario.

**Comment by haorenW1025** [comment]
Okay make sense. I'll look into how deoplete handle this situation. Thanks for your input:)

**Comment by haorenW1025** [comment]
Sorry for pending this issue, it should be fixed now. Please update and check:)

**Comment by JanValiska** [comment]
Everything looks correct except completion of hidden files(files starting with dot). If i start typing `.` then hidden files are suggested but when i select one hidden file for example `.Xresources` the `..Xresources` is completed. I don't know if it is problem with my neovim configration. Please let me know if this behavior is present also in your env. Thanks.

**Comment by JanValiska** [comment]
With `./.Something` it works fine. hm.

**Comment by haorenW1025** [comment]
Yeah that's a known issue. At least completing with white spaces should be fine. Please follow #23 for other path completion related things.

**Comment by JanValiska** [comment]
Thank you very much!
