### ISSUE TITLE
 Test validity of highlight ranges

### ISSUE THREAD

**Issue by Slyces** [haorenW1025/completion-nvim#57]
Hi guys. Following on #52 that had an issue with vimls providing -1 as start/end of highlight range, I had a similar bug on pyls.

I'm working on a codebase I didn't write of a somewhat beginner python developer, and I had a sample similar to the following:
```python
if True:
    '''
    some text
    '''
    print("hello_world")
```

On this sample of code (that shouldn't happen), pyls sends:
```
{
    code = "W0105",
    message = "[pointless-string-statement] String statement has no effect",
    range = {
      end = {
        character = 8,
        line = 3
      },
      start = {
        character = -1,
        line = 3
      }
    },
    severity = 2,
    source = "pylint"
  }
```
The problematic line here is `start.character = -1`. This value goes to the function responsible for highlighting, that throws:
```
Error executing vim.schedule lua callback: ...are/nvim/plugged/diagnostic-nvim/lua/diagnostic/util.lua:17: Column value outside range
```

Please note that this function is a copy from nvim's runtime, so without the plugin, it's neovim's identical function that throws that error:
```
Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:628: Column value outside range
```

So #52 was solved by a server-side issue (that was extremely quickly fixed on vimls side), I guess this should be the preferred way to solve this issue as well (I will forward it to pyls).
However, as other cases like this one might appear, could it be interesting to find a non-intrusive way to log this error, as it was actually spamming my messages and made coding quite difficult.

P.S: I'm posting the issue here and not in `diagnostic-nvim` as it follows #52.

**Comment by haorenW1025** [comment]
I push my fix in `diagnostic-nvim`, not sure how neovim and pyls deal with this problem though. Close this on my side.
