### ISSUE TITLE
readme: several autocommands?

### ISSUE THREAD

**Issue by aeosynth** [haorenW1025/completion-nvim#59]
Hi, not a critical issue but the wording is confusing:

> completion-nvim **requires** several autocommands set up to work properly

it seems to work fine without any autocommands; the autocommand is only required for use w/o lsp. `diagnostic-nvim` has the same wording, and also works fine w/o autocommands.

**Comment by haorenW1025** [comment]
Hmm I think there is some misunderstanding. Both of the plugins *does* require autocommands, but is set up in the `on_attach` function. Without the autocmd setup in `on_attach` many stuff in both of the plugins won't work as expected.
