### ISSUE TITLE
Start completion with a min of characters typed or manually

### ISSUE THREAD

**Issue by carlitux** [haorenW1025/completion-nvim#6]
It would be very helpful to be able to set up this or keep it by default.

I think:

- Improves quick editing
- Allow completions on import syntaxes

**Comment by haorenW1025** [comment]
I add an option to set trigger character lenght in the latest branch. You can set it by
```.vim
let g:completion_trigger_keyword_length = 1   "this is the defualt value
```
I've encounter some issue when doing the manually trigger completion though, still need some time to get it work as expected.

**Comment by haorenW1025** [comment]
Manually trigger option should be ready, check README for detail information, please update and check:)

**Comment by carlitux** [comment]
Thank you very much!!!!!

Really a very fast response it is a great plugin.

**Comment by haorenW1025** [comment]
Thanks for the kind word! Close this for now, feel free to reopen if you encounter any issue!
