### ISSUE TITLE
Conflict with auto-pairs plugin

### ISSUE THREAD

**Issue by lourenci** [haorenW1025/completion-nvim#62]
I don't know why, but this plugin breaks the `jiangmiao/auto-pairs` feature of breaking a new statement in a new line when the user presses ENTER:

Before install this plugin:
```
// from
it('test', () => {<cursor><CR>})
//to
it('test', () => {
  <cursor>
})
```

After install this plugin:
```
// from
it('test', () => {<cursor><CR>})
//to
it('test', () => {
<cursor>})
```

Do you have any idea how can I solve that?

Thank you. I'm able to use the native `nvim-lsp` thanks to your plugin.

**Comment by haorenW1025** [comment]
Hmm I think the `completion_confirm_key` is overwriting the auto pair functionality. Can you try if setting this works?
```vim
let g:completion_confirm_key_rhs = "<C-R>=AutoPairsReturn()<CR>"
```

**Comment by lourenci** [comment]
Don't. This is the result:

![image](https://user-images.githubusercontent.com/2339362/81926019-b9fada00-95b7-11ea-86b7-b0d804d7d9a3.png)

**Comment by haorenW1025** [comment]
My fault...you should add an escape key
```vim
let g:completion_confirm_key_rhs = "\<C-R>=AutoPairsReturn()<CR>"
```

**Comment by lourenci** [comment]
I tried too, it does not happen nothing at all. The cursor stays in the same position as no enter has been pressed.

**Comment by haorenW1025** [comment]
Okay I should make a fix, sorry for the noise.

**Comment by lourenci** [comment]
No problem at all. Thanks for the library.

**Comment by haorenW1025** [comment]
I made a backup way to set up confirm key, use the following
```vim
let g:completion_confirm_key = ""
inoremap <expr> <cr>    pumvisible() ? "\<Plug>(completion_confirm_completion)" : "\<cr>"
```
Also `jiangmiao/auto-pairs` set up mapping according to your history, you should delete the files in `~/.local/nvim/view/` or your `viewdir`(see `:h viewdir`).

**Comment by lourenci** [comment]
It does not work, even cleaning the view path up.

**Comment by lourenci** [comment]
My bad, I haven't configured the `let g:completion_confirm_key`. Thanks for that.
