### ISSUE TITLE
Odd behavior after multiples tabs

### ISSUE THREAD

**Issue by ckipp01** [haorenW1025/completion-nvim#63]
When using the recommended settings in the readme in order to use `<Tab>` to filter through the completion options, I get odd behavior when I filter through the completion items only if there is something that already exists where I'm trying to completion. For example:

```scala
import jav@@
```
~At this point above, I can circulate through the options with no issue, and select the one that I want.~

After I complete `java`, if I think attempt to continue to completion, I get odd behavior when doing completions:

```scala
import java.ti@@
```

Here is a couple gifs of the behavior I'm referring to:

![2020-05-14 11 07 20](https://user-images.githubusercontent.com/13974112/81915620-20d9bc80-95d3-11ea-9427-deba6cff1dca.gif)

![2020-05-14 10 58 03](https://user-images.githubusercontent.com/13974112/81915123-782b5d00-95d2-11ea-8251-56c48766c6f5.gif)

**How to reproduce**
This is happening with Metals. Probably the easiest way to reproduce this would be to do the following:

- `LspInstall metals`, which which will install metals.
- Then you can [nvim-metals](https://github.com/ckipp01/nvim-metals) which will provide you some necessary commands for a Scala workspace.
- You can use [this minimal project](https://github.com/ckipp01/metals-minimal-sbt).
- Just open the `build.sbt` file, `nvim build.sbt`. Then you can issue a `:BuildImport` command which will import the build.
- Then navigate to any Scala file in the project and attempt to do a package import like I did in the gif.

**Expected behavior**
I would expect the completions to work the same if it is a base completion or one coming after a `.`

**Comment by ckipp01** [comment]
Apparently the above is a bit wrong. Even trying to complete `java` does the behavior. The completion on `import` has no issues though.

![2020-05-14 11 09 10](https://user-images.githubusercontent.com/13974112/81915888-71e9b080-95d3-11ea-9237-b4c851870f30.gif)

**Comment by haorenW1025** [comment]
Can you provide a link to a minimal project? I'm totally new to scala so it's hard for me to reproduce:(

**Comment by ckipp01** [comment]
> Can you provide a link to a minimal project? I'm totally new to scala so it's hard for me to reproduce:(

ahhh sorry, I mentioned it and then totally didn't include he link 😆 sorry. https://github.com/ckipp01/metals-minimal-sbt

**Comment by haorenW1025** [comment]
I can't reproduce with the minimal config, but I update a possible fix. Please check if it resolve your issue.

**Comment by ckipp01** [comment]
Hello! The update didn't fix it, however, with the following configuration, I'm unable to reproduce...

So it must be something with my setup.

```vim
call plug#begin('~/.vim/plugged') 
    Plug 'neovim/nvim-lsp'
    Plug 'haorenW1025/completion-nvim'
call plug#end()
lua require'nvim_lsp'.sumneko_lua.setup{on_attach=require'completion'.on_attach}
au Filetype lua setl omnifunc=v:lua.vim.lsp.omnifunc
" Use <Tab> and <S-Tab> to navigate through popup menu
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

" Set completeopt to have a better completion experience
set completeopt=menuone,noinsert,noselect
```

**Comment by haorenW1025** [comment]
Hmm that's weird...Do you have a link to your config? Maybe I can look through and see if I can find the possible cause of this issue.

**Comment by ckipp01** [comment]
So I found the issue, but I don't know why it conflicts. Since a lot of Scala signatures are long, I use the below to override the `textDocument/hover` callback:

https://github.com/ckipp01/nvim-metals/blob/377c9a3d7afa3759a99b14df3d5a64f49565806a/lua/metals.lua#L69-L94

At a glance, any idea why this happens?

**Comment by haorenW1025** [comment]
Okay that explains it. It’s because I also have to overwrite the hover callback to make it auto close when changing hover items, but your overwrite function overwrite it again... I’ll try to fix this since this may happens to other users who wants to customize their hover callback.

**Comment by ckipp01** [comment]
ahh, ok, that does make sense. Honestly, if you're already providing it, would you be willing for you callback to take into account the viewport width and possibly wrap? If so, then I wouldn't even need my own custom callback.

**Comment by haorenW1025** [comment]
Yeah that would be nice, I'll implement that, thanks for the suggestion:)

**Comment by haorenW1025** [comment]
It should no longer overwrite user-defined hover function.

> would you be willing for you callback to take into account the viewport width and possibly wrap?

Can you provide a example code for the wrap?  I want to check if it works on my side.

**Comment by ckipp01** [comment]
Sure, do you want just the json completion or do you actually want it in a workspace? If so, I can add a long signature to the repo I shared before and push it up.

**Comment by haorenW1025** [comment]
Using the repo would be nice, thanks!

**Comment by ckipp01** [comment]
Alright, if you pull the repo above I added a `superLongMethodToTestHover` that you can trigger a hover on line 4. I first came across this issue when I was using split and had to hover on a long method like this.

**Comment by haorenW1025** [comment]
It should be done in the latest commit, please update and check:)

**Comment by ckipp01** [comment]
> It should be done in the latest commit, please update and check:)

So when I remove my callback and just use the one you're providing, it looks like it's not wrapping. For example you can see that it's going off the screen.

![2020-05-14 18 56 40](https://user-images.githubusercontent.com/13974112/81963144-fe689300-9614-11ea-979f-2a21c063429b.gif)

**Comment by haorenW1025** [comment]
Oh this is expected. I need to avoid overwriting user defined hover function so I only modified the auto hover part. You should still use your custom callback for other circumstances.

**Comment by ckipp01** [comment]
> Oh this is expected. I need to avoid overwriting user defined hover function so I only modified the auto hover part. You should still use your custom callback for other circumstances.

Ah gotcha. Hm, then I guess my callback is still conflicting in some way because I'm still getting the behavior where multiple tabs will cause me to jump into the floating window and complete again like shown in the first gif.

**Comment by haorenW1025** [comment]
This takes way longer than I expected...It turns out if you set custom callback function through `setup` function provided by `nvim_lsp`, the function will be in the `client` object instead of changing `vim.lsp.callback`. The latest commit should work, I've tested it with your config in `nvim-metals`.

**Comment by ckipp01** [comment]
> This takes way longer than I expected...

😬 it is much appreciated!

> It turns out if you set custom callback function through `setup` function provided by `nvim_lsp`, the function will be in the `client` object instead of changing `vim.lsp.callback`. The latest commit should work, I've tested it with your config in `nvim-metals`.

Awesome. Just checked and this does indeed work great. Thank you! 👍
