### ISSUE TITLE
Allow for `additionalTextEdits` in completion items.

### ISSUE THREAD

**Issue by ckipp01** [haorenW1025/completion-nvim#64]
**Is your feature request related to a problem? Please describe.**
Current the built-in lsp support doesn't take into account that completions may have `additionalTextEdits` in them. I created a feature request for this already in nvim, and you can see the suggestion for a work around [here](https://github.com/neovim/neovim/issues/12310#issuecomment-628269290). When playing around with it I realized that you already have something pretty similar to this with your `confirmCompltion()` function.

https://github.com/haorenW1025/completion-nvim/blob/7aedc744e2c7cd615a60b7b59d3e3c6a5491154e/lua/completion.lua#L51-L67

It'd be cool to also have this check for `additionalTextEdits`, and if so, apply them.

**Describe the solution you'd like**
Piggyback off `confirmCompletion()` and account for `additionalTextEdits`.

**Describe alternatives you've considered**
Locally listen for `CompleteDone` and have a function locally that does this.

**Comment by haorenW1025** [comment]
Yeah that's definitely possible. I'll try to implement this.

**Comment by haorenW1025** [comment]
I've shamelessly used the code snippet from the discussion you mentioned and it should be working now, please update and check:)

**Comment by ckipp01** [comment]
Cool, so I just gave this a try on the following completion:
```json
    {
      "label": "Instant - java.time",
      "kind": 9,
      "detail": " java.time",
      "sortText": "00004",
      "filterText": "Instant",
      "insertTextFormat": 1,
      "textEdit": {
        "range": {
          "start": {
            "line": 10,
            "character": 10
          },
          "end": {
            "line": 10,
            "character": 16
          }
        },
        "newText": "Instant"
      },
      "additionalTextEdits": [
        {
          "range": {
            "start": {
              "line": 1,
              "character": 0
            },
            "end": {
              "line": 1,
              "character": 0
            }
          },
          "newText": "\nimport java.time.Instant\n"
        }
      ],
      "data": {
        "symbol": "java/time/Instant#",
        "target": "file:/Users/ckipp/Documents/scala-workspace/metals-minimal-sbt/?id\u003droot"
      }
    }
```

And I get the following error:

```
|| Error detected while processing CompleteDone Autocommands for "<buffer=3>":
|| E5108: Error executing lua ...rs/ckipp/.vim/plugged/completion-nvim/lua/completion.lua:59: attempt to perform arithmetic on upvalue 'lnum' (a table value)
```

**Comment by haorenW1025** [comment]
It should be fixed now(I've checked with the given completion), please update and check.

**Comment by ckipp01** [comment]
Yes! This indeed does work. Thanks so much for implementing this! I appreciate all the work you are putting into this plugin 👍

**Comment by haorenW1025** [comment]
No problem:) I'll also make an option for this and having it on by default in case people doesn't want this feature.
