### ISSUE TITLE
[Question] Sorting

### ISSUE THREAD

**Issue by kristijanhusak** [haorenW1025/completion-nvim#67]
Hey,

why do you suggest in the readme to not set sorting to `none` when using multiple sources? I want results to be sorted by the order they are defined in config, and it looks like it's working fine.

Is there some other issue that it's causing?

Thanks!

**Comment by haorenW1025** [comment]
If that's the case then setting it to `none` is fine. I just think that most people wouldn't want that behavior. If that's misleading, I can take those lines out:)
