### ISSUE TITLE
hover() breaks after using completion menu

### ISSUE THREAD

**Issue by steelsojka** [haorenW1025/completion-nvim#70]
- Please read through [this section](https://github.com/haorenW1025/completion-nvim/wiki/trouble-shooting) before posting a bug report.

This only happens after the completion menu has popped up at least once.

![Peek 2020-05-16 13-38](https://user-images.githubusercontent.com/2062154/82127774-c760c180-977b-11ea-91fe-32e39960585f.gif)

**My testing minimal init.vim**
Post your init.vim to help me reproduce this issue

```
call plug#begin('~/.local/share/nvim/plugged') 
    Plug 'neovim/nvim-lsp'
    Plug 'haorenW1025/completion-nvim'
call plug#end()
lua require'nvim_lsp'.tsserver.setup{on_attach=require'completion'.on_attach}
au Filetype lua setl omnifunc=v:lua.vim.lsp.omnifunc
" Use <Tab> and <S-Tab> to navigate through popup menu
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

" Set completeopt to have a better completion experience
set completeopt=menuone,noinsert,noselect

```

**How to reproduce**
1. Located a symbol and remove it.
2. Start typing to bring up the completion menu.
3. Select the same symbol from the list
4. Try to bring up the `hover` popup `:lua vim.lsp.buf.hover()`

**Expected behavior**
Popup window appears with documentation

**Comment by haorenW1025** [comment]
Can you update to the latest commit and see if it fix it?

**Comment by steelsojka** [comment]
Updated and that fixed it! Thanks for the super fast turn around.
