### ISSUE TITLE
vim.schedule error

### ISSUE THREAD

**Issue by bryall** [haorenW1025/completion-nvim#73]
- Please read through [this section](https://github.com/haorenW1025/completion-nvim/wiki/trouble-shooting) before posting a bug report.

**My testing minimal init.vim**
```vim
call plug#begin('~/.vim/plugged')
    Plug 'neovim/nvim-lsp'
    Plug 'haorenW1025/completion-nvim'
call plug#end()
lua require'nvim_lsp'.pyls_ms.setup{on_attach=require'completion'.on_attach}
au Filetype lua setl omnifunc=v:lua.vim.lsp.omnifunc
" Use <Tab> and <S-Tab> to navigate through popup menu
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

" Set completeopt to have a better completion experience
set completeopt=menuone,noinsert,noselect
```

**How to reproduce**
nvim -u test.vim <python file>
and then try to auto complete a python function. Neovim locks up with the following error keeps seems to be in a loop:
```
Error executing vim.schedule lua callcack: VimE731: using Dictionary as a String
```

let me know if anything else I could test out, thanks

**Expected behavior**
no error messages

**Comment by haorenW1025** [comment]
Please update to the newest nightly release of neovim or build neovim from source. I think that would solve this issue.

**Comment by hrsh7th** [comment]
I had same issue and the issue was solved by updating neovim.

**Comment by bryall** [comment]
yep, I thought I updated to the latest neovim but apparently 'brew upgrade neovim' does not fetch the new head you have to specify --fetch-head option 

but upgrading to the head, I do not see this problem

**Comment by jnvrs** [comment]
upgrading nvim has no effect on the issue
