### ISSUE TITLE
Trigger completions on character removal

### ISSUE THREAD

**Issue by doubleloop** [haorenW1025/completion-nvim#75]
It would be nice if completions were triggered also after characters are removed (for example with backspace or <c-w>).

**Comment by haorenW1025** [comment]
Hmm that's not hard to implement, but I disable it by purpose cause I found it a little disturbing. Also you can always triggered the completion with one keystroke(see README if you don't know this) so it shouldn't be very inconvenient.

**Comment by doubleloop** [comment]
Maybe this could be optional. AFAIK it is default behavior for completers in most code editors I know. This is especially useful when you are searching for some method in large module (like numpy or tensorflow), and you are not sure what is the name of the method (you type `np.somename`, if it is not there, you can delete `somename` and type `othername` while popup is still opened).

**Comment by haorenW1025** [comment]
Sorry for the delay, can you please try #84 and see if it works for you?

**Comment by doubleloop** [comment]
Just tested and it works as expected. Thx!

**Comment by haorenW1025** [comment]
Thanks:) I'll fix some minor things and merge it ASAP.

**Comment by haorenW1025** [comment]
PR was merged, closing this for now:)
