### ISSUE TITLE
Unhandled error when no space for hoover window

### ISSUE THREAD

**Issue by doubleloop** [haorenW1025/completion-nvim#76]
```
Error executing vim.schedule lua callback: ...re/nvim/plugged/completionnvim/lua/completion/hover.lua:217: 'width' key must be a positive Integer
```

This happens when `g:completion_enable_auto_hover` is set to 1 and there is no space for hoover window.
![Screenshot from 2020-05-21 16-03-43](https://user-images.githubusercontent.com/2602750/82566765-b1d50880-9b7c-11ea-8f62-d8db324bc4b1.png)

**Comment by haorenW1025** [comment]
Please update and checked if it's fixed.

**Comment by doubleloop** [comment]
Confirm it is fixed.
