### ISSUE TITLE
Add the ability to check if there is an item selected

### ISSUE THREAD

**Issue by Shatur95** [haorenW1025/completion-nvim#77]
**Is your feature request related to a problem? Please describe.**
I would like to use `<CR>` to apply completion only if any item selected and insert a new line otherwise. Currently pressing `<CR>` if there is not item selected will just close completion window.

**Describe the solution you'd like**
I would like to have a function to check if there is an item selected. To map something like the following:
`imap <expr><CR>  completion#is_item_selected() ? completion#completion_confirm() : "\<CR>"`

**Comment by Shatur95** [comment]
Hm... I see that `<CR>` mapping is internal, so even if you provide such API to check - it will be not possible to map.

Maybe it would be better to provide an option to close completion window and insert a newline instead of only closing completion window (default behavior)?

**Comment by haorenW1025** [comment]
Actually I'm planning to move the mapping out from internal(see issue #62). I'm trying to have a basic solution now, but I'm quite busy these days...Maybe you'll have to wait a little bit:(

**Comment by Shatur95** [comment]
Good idea, I think. This will make the plugin more flexible.

Not a problem, thanks for the attention. So, will wait for moving this mapping from external first.

**Comment by haorenW1025** [comment]
Sorry for the late replied, I personally think we should still keep the default mapping because it does provide an out-of-box experience. But we can enable external setting if `g:completion_confirm_key` is an empty string. You can try putting this in your config and see if it works.
```vim
let g:completion_confirm_key = ""
imap <expr> <cr>  pumvisible() ? complete_info()["selected"] != "-1" ?
                 \ "\<Plug>(completion_confirm_completion)"  : "\<c-e>\<CR>" :  "\<CR>"
```

**Comment by Shatur95** [comment]
Thanks, it works, just what I need. Will you add an option for it?

**Comment by haorenW1025** [comment]
Hmm maybe I'll add a guide in the README for this, this should deprecated the `g:completion_confirm_key_rhs` option.

**Comment by Shatur95** [comment]
Good idea, I think.
