### ISSUE TITLE
Buffer completion

### ISSUE THREAD

**Issue by Shatur95** [haorenW1025/completion-nvim#78]
**Is your feature request related to a problem? Please describe.**
Sometimes is very convenient to have basic word completion. A lost of editors have this feature. Also Vim completion plugins such as mucomplete or asyncomplete.vim have buffer completion source.

**Describe the solution you'd like**
I suggest to add buffer completion :)

**Describe alternatives you've considered**
I noticed that you have `ins-complete` support, but is it possible to complete buffer words with it? Sorry, I am very newbie in it :)

**Comment by haorenW1025** [comment]
Yeah you can use `ins-complete` to complete buffer words with `<c-n>` and `<c-p>` if you have `set complete=.,w,b,u`(see `:h complete` for detailed information). There are a lot of limit with the `ins-complete` though(it's not async, couldn't combine it with other completion source) but I currently have no time writing another source for it. It'll be nice if someone can help though.

**Comment by Shatur95** [comment]
Thanks for explanation!

**Comment by steelsojka** [comment]
I created a PR for this feature https://github.com/haorenW1025/completion-nvim/pull/94. I too was missing this from Coc.
