### ISSUE TITLE
Add support for vim-vsnip

### ISSUE THREAD

**Issue by Shatur95** [haorenW1025/completion-nvim#81]
**Is your feature request related to a problem? Please describe.**
The readme says that currently only `UltiSnips` and `Neosnippet` is supported for snippets and `vim-vsnip` can be used for LSP snippets expansion. But `vim-vsnip` can have user-defined snippets too with very convenient syntax. But snippets from it is not displayed. It would be nice to use a single plugin for LSP snippets and for user snippets.

**Describe the solution you'd like**
Could you add a support for `vim-vsnip` as for `UltiSnips` and `Neosnippet`?
Something like the ability to specify `vim-vsnip` in `g:completion_enable_snippet`.

**Comment by haorenW1025** [comment]
That's definitely possible. @hrsh7th is there an api that I can get all the snippets available for the current buffer?

**Comment by hrsh7th** [comment]
Currently, no. But it should be implemented. I will implement it.

**Comment by Shatur95** [comment]
Should the integration exist in [vim-vsnip-integ](https://github.com/hrsh7th/vim-vsnip-integ) or here? I mean is I opened the issue in the right place?

**Comment by hrsh7th** [comment]
I've added `vsnip#get_complete_items(bufnr)` to vsnip.
https://github.com/hrsh7th/vim-vsnip/commit/e5c8019e6c54b4bd79d9c7c2dc3ecff1540dd443#diff-29608c6ada9f413a1379505a0c7556faR131

**Comment by haorenW1025** [comment]
@Shatur95 It will be nice if you try #82 and gave me some feedback.

**Comment by haorenW1025** [comment]
closed by #82.
