### ISSUE TITLE
Fuzzy Matching Issues

### ISSUE THREAD

**Issue by bryall** [haorenW1025/completion-nvim#83]
- Please read through [this section](https://github.com/haorenW1025/completion-nvim/wiki/trouble-shooting) before posting a bug report.

**My testing minimal init.vim**

**How to reproduce**
fuzzy matching is turned on
Starting typing a word in a buffer
I see my LSP (I am developing) return completion items to neovim, however they are not displayed.
The word I am typing is fuzzy matched to the item I want to complete
But I do not see a pop up unless I type the extract string

**Expected behavior**
See the fuzzy completion item.

I assume I am not sending the correct thing back to neovim from my LSP, but what conditions will hide completions items return from the LSP?

Thanks for the great plugin

**Comment by haorenW1025** [comment]
Hmm it would be nice if you provide your lsp and give me a guide on how to reproduce it. Otherwise it's hard for me to find the cause.

**Comment by bryall** [comment]
figured it out
