### ISSUE TITLE
complete function's parameters after complete a function

### ISSUE THREAD

**Issue by ataul443** [haorenW1025/completion-nvim#85]
It would be really nice if I get function signature placeholders after completion of a function. I am using gopls right now, and there is nothing like that on default.

**Comment by haorenW1025** [comment]
Hmm can you give me an example of `signature placeholders`? Not quite sure what you means.

**Comment by ataul443** [comment]
Lets for an example, here is a function declaration in rust -
`fn largest(list: &[i32]) -> i32;`

Right now, a completion will only gives me this - 
`largest()`

It would be nice if I get a completion like this -
`largest(list)`

Where `list` can be a placeholder value like in snipets.

**Comment by haorenW1025** [comment]
Yeah it'd be nice. But that requires me to create a parser for lsp snippets, handle placeholders and jump between snippets, probably should handle nested snippets... It seems to be too much work for me and kind of out of the scope of  `completion-nvim`. I'll recommend using [vim-vsnip](https://github.com/hrsh7th/vim-vsnip) which works pretty great on my side and also integrate out of the box with completion-nvim(requires [vim-vsnip-integ](https://github.com/hrsh7th/vim-vsnip-integ)). Also there is a WIP [snippets.nvim](https://github.com/archseer/snippets.nvim) written in lua aims to solve this.

**Comment by ataul443** [comment]
I see. no issues. thanks for the recommendations.
