### ISSUE TITLE
Do not show snippet if it have the same name as the completion keyword

### ISSUE THREAD

**Issue by Shatur95** [haorenW1025/completion-nvim#86]
**My testing minimal init.vim**

```vim
packadd nvim-lsp
let g:completion_enable_snippet = 'vim-vsnip'

lua << EOF
  local nvim_lsp = require'nvim_lsp'
  local custom_attach = function()
    require'completion'.on_attach()
  end

  nvim_lsp.vimls.setup{on_attach = custom_attach}
EOF
```

You need to setup [vim-language-server](https://github.com/iamcco/vim-language-server).

**How to reproduce**
1. Open any `.vim` file.
2. Type `fu`.

**Expected behavior**
For `fu` suggested function snippet (from LSP, not user-defined) and function word.
![изображение](https://user-images.githubusercontent.com/22453358/82998444-686b3a00-a010-11ea-960a-84593ab0a11e.png)
_(screenshot form `vim-compete`)_

**Actual behavior**
For `fu` suggested only `function` keyword.
![изображение](https://user-images.githubusercontent.com/22453358/82998964-0e1ea900-a011-11ea-9903-fdf29a871ea3.png)

**Comment by haorenW1025** [comment]
Okay I think I know the issue. You have to install `vim-vsnip-integ` to get the snippet items show up, otherwise `completion-nvim` will filter out the snippet items(since it's annoying for now). Can you try it with `vim-vsnip-integ` again?

**Comment by Shatur95** [comment]
The tests above was with `vim-vsnip-integ`.

**Comment by hrsh7th** [comment]
Your setting has no `snippetSupport = true` so the server does not returns snippet items.

```viml
  lua require'nvim_lsp'.vimls.setup{
  \   capabilities = {
  \     textDocument = {
  \       completion = {
  \         completionItem = {
  \           snippetSupport = true
  \         }
  \       }
  \     }
  \   },
  \ }
```

**Comment by Shatur95** [comment]
Thank you, missed it! Sorry for bothering.
