### ISSUE TITLE
Completion snippets not getting expanded.

### ISSUE THREAD

**Issue by xanderio** [haorenW1025/completion-nvim#93]
I having a  problem where completion snippets aren't expended correctly and the snippet markers are inserted into the buffer.

versions:
nvim neovim/neovim@91e41c8
completion-nvim: b411b46

As a quick workaround I'm currently using neovim/neovim@2ca8f02

It looks like the 'bug' only happens when running at least neovim/neovim@5a9226c

**My testing minimal init.vim**
```lua
local lsp = require'nvim_lsp'

local on_attach_vim = function()
  require'completion'.on_attach()
  require'diagnostic'.on_attach()
end


lsp.rust_analyzer.setup{
  on_attach = on_attach_vim
}
```

nvim version: neovim/neovim@91e41c8
completion-nvim: b411b46
@xanderio

**How to reproduce**
1. install nvim with at least neovim/neovim@5a9226c
2. install rust-analyser
3. setup completion
4. complete something in a file

** Current behaviour**
`self.insert_notify(${1:notify})$0`

**Expected behaviour**
The snippet getting processed and the cursor getting set on the placeholders.

**Comment by haorenW1025** [comment]
Yeah that's the expected behavior now, `completion-nvim` doesn't do any snippets parsing. You'll need `vim-vsnip` and `vim-vsnip-integ` for that, and also I think rust-analyzer is quite sloppy on marking the snippets items so it'll be more annoying to deal with.

**Comment by xanderio** [comment]
Even with `vim-snip` and ´vim-snip-integ` install this doesn't work. I'll forward this issue to rust-analyzer.

**Comment by haorenW1025** [comment]
Quite weird because it seems working on my side(sorry for the bad gif...)
![Peek 2020-06-03 00-35](https://user-images.githubusercontent.com/35623968/83545866-68989780-a532-11ea-912c-19b4b5aac022.gif)

**Comment by xanderio** [comment]
Well this is awkward. I forget that you need to confirm the completion.

**Comment by kosayoda** [comment]
I have the exact same issue. May I know what you mean by "confirm the completion"? To my understanding, it is the Enter key by default.

Pressing the Enter key while having a completion item with a snippet  selected (in my example, `println!($0)`) just leaves me in insert mode *after* the closing parenthesis.

**Comment by haorenW1025** [comment]
Yeah enter is the default key. @kosayoda Do you have vim-vsnip and vim-vsnip-integ install? If so, feel free to open a new issues.
