### ISSUE TITLE
Add the ability to specify item icons

### ISSUE THREAD

**Issue by Shatur95** [haorenW1025/completion-nvim#96]
**Is your feature request related to a problem? Please describe.**
In all editors functions / method / text items for completions have icons instead of text. For example, how completion looks in VSCode:
![изображение](https://user-images.githubusercontent.com/22453358/83648151-61b76680-a5be-11ea-97c2-f42fbf221401.png)

**Describe the solution you'd like**
Is it possible to allow user to specify custom text-based icons? Something like with signs, but for completion items. It would make more nice look :)

**Comment by Shatur95** [comment]
There is undocumented `g:completion_customize_lsp_label`.
Did not know about it, sorry.

**Comment by haorenW1025** [comment]
That's fine, it's my fault for not documented it well. Also you might be interesting in [wik](https://github.com/haorenW1025/completion-nvim/wiki/Customizing-symbolKind-or-CompletionItemKind) where there is a customization guide on symbol that works per server basic and doesn't require using `completion-nvim` stuff.

**Comment by Shatur95** [comment]
Did not know about it! Thanks. But both approaches will not for custom sources. I created an issue for it in [completion-buffers](https://github.com/steelsojka/completion-buffers/issues/2).

**Comment by Shatur95** [comment]
Now `completion-buffers` support `g:completion_customize_lsp_label`.

**Comment by haorenW1025** [comment]
Nice! I saw your issues in `completion-buffers`. You're icons selection is neat! Mind if I put it in wiki for a reference?

**Comment by Shatur95** [comment]
Of course!
[Here](https://github.com/Shatur95/neovim-config/blob/03f78e010991df32af2b892a8a4d044495eb7e01/plugin/completion.vim#L15) is the newest version.
[Here](https://www.nerdfonts.com/cheat-sheet) is convenient icon cheat sheet.
