### ISSUE TITLE
<CR> doesn't always enter a newline with auto_popup

### ISSUE THREAD

**Issue by nhooyr** [haorenW1025/completion-nvim#99]
I'm seeing some odd behaviour only with the `auto_popup` enabled.

About 50% of the time when it appears but I don't want it and I hit `<CR>` for a newline, nvim just closes completion menu and doesn't insert a newline.

With manual triggering, this never happens.

**Comment by nhooyr** [comment]
i.e with manual triggering if I start the popup, do not select anything and then hit `<CR>`, the popup is closed and a newline is inserted.

**Comment by Shatur95** [comment]
Try the following: https://github.com/haorenW1025/completion-nvim/issues/77#issuecomment-633434069

**Comment by nhooyr** [comment]
So I already have `let g:completion_confirm_key = ""`.

I don't see a <CR> binding from completion-nvim being registered so I'm not sure how this is happening.

**Comment by nhooyr** [comment]
Adding your keybindings seems to fix it

🤷

**Comment by nhooyr** [comment]
Is `<C-t>` supposed to act as as the confirm key even if it hasn't been set as the completion key?

I have no mapping for `<C-t>` and `imap <C-t>` confirms that but it acts as though it is mapped. When I hit `<C-t>` after selecting a function call, it lets me fill in the args as though it's a snippet.

**Comment by haorenW1025** [comment]
@nhooyr It shouldn't and I tried but it doesn't work on my side.
I'll fix the confirm key behavior though. It should always close the popup menu and insert enter.

**Comment by nhooyr** [comment]
> I'll fix the confirm key behavior though. It should always close the popup menu and insert enter.

Awesome thanks!

I have `<C-e>` mapped to `<End>` and that also works as the completion confirm key for me.

**Comment by nhooyr** [comment]
Also to clarify those two keys only complete lsp function snippets with `vim-vsnip`.

Neosnippet snippets still require me to use whatever key I have set as the confirm key or the mapping you posted above.

**Comment by nhooyr** [comment]
So then one more thing here would be

- [ ] Docs on completion_confirm_completion

**Comment by haorenW1025** [comment]
I guess `vim-vsnip` handles that differently since it'll get expanded even if I just type `(` when inserting a function(which is actually pretty good).

**Comment by haorenW1025** [comment]
@nhooyr Please try #102 :)

**Comment by haorenW1025** [comment]
#102 is merged, should be fine now. Feel free to reopen if there's still any issues.

**Comment by nhooyr** [comment]
Confirmed fixed!

Thank you so much @haorenW1025 

You should consider signing up for Github Sponsors, I'd love to support your work.
